### ISSUE TITLE
Process asset returning null

### ISSUE THREAD

**Issue by swiatek25** [contentful/contentful-management.java#62]
Hi, 
We are doing asset management part of application and encountered problem with this flow:
1. Create asset with `cmaClient.assets().create(spaceId, asset)`
2. Process asset (upload url) with `cmaClient.assets().process(asset, locale)`

`asset` parameter in second step comes from step 1. Unfortunately second step returns null and subsequent call to `cmaClient.assets().fetchOne(spaceId, id)` does not return `url` attribute in asset object (the one pointing to contentful Image API) 

We are using : 1.3.0 version of SDK

**Comment by mariobodemann** [comment]
Hello @swiatek25,

sorry for the incredible long delay, I don't know how this message slipped us.

To answer your question: If you process an asset your app has to wait till fetching it returns an asset with the `url` field set, and not having the `upload` field. Once the `url` field is present and set, you can start using the asset as normal. 

The `process` call returns Null, since the Contentful returns immediately so you can progress with you work, while the asset will get processed...

Greetings and sorry again,
Mario

**Comment by mariobodemann** [comment]
I close this issue for now. If there are more questions popping up, please do not hesitate to reach out to us again...
