### ISSUE TITLE
Space.getSpaceId() returns null

### ISSUE THREAD

**Issue by timrobertson100** [contentful/contentful-management.java#71]
This should not give a null value as a spaceID:

```
      CMAArray<CMASpace> result = cmaClient.spaces().fetchAll();
      for (CMASpace space : result.getItems()) {
        LOG.info("Space ID: {}", space.getSpaceId()); 
      }
```

A workaround for this is to use ```String.valueOf(space.getSys().get("id"));```

**Comment by mariobodemann** [comment]
Hey,

hmm, that is an interesting use case. Right now `getSpaceId()` on a space does not return its `id` but the id its space has. Since a space cannot be inside of another space, `getSpaceId()` returns `null`. 

So a workaround would the one you suggested, or using `space.getId()` (or `space.getResourceId()`, depending on SDK version).

**Comment by timrobertson100** [comment]
Thanks Mario - it was just the first thing I did really and thought it was a bit unintuitive given the method name.  I know this is subjective... I'd vote for making `space.getSpaceId()` return it's own ID but otherwise if you think this is inconsistent then please just close this as `won't fix`.
